# Generated by Django 5.1 on 2024-09-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0003_alter_teacher_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='phone_number',
        ),
    ]
