# Generated by Django 5.1 on 2024-09-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_enrolled', models.BooleanField(default=True)),
                ('enrollment_date', models.DateField()),
                ('GPA', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
